
@startuml

component "Company A" as pComp1 {

  database "Screen" as sScreen

  actor "Dev" as pAct1
  component "Developing()" as pDev1
  frame "Presenting()" as pPres

  pAct1 <-> pDev1
  pDev1 -> pPres
  pPres -> sScreen
}

rectangle "Release" as sRel {
  database "Func A\nFunc B\nFunc C2" as sFunc2
  file "Release\nNotes" as sInfo
}

database "Func A\nFunc B\nFunc C1\nFunc D" as sFunc1

component "Company B" as pComp2 {

  actor "Dev" as pAct2
  component "Developing()" as pDev2
  frame "Calculating()" as pCalc

  pAct2 <-> pDev2
  pDev2 -> pCalc
}

sInfo .r[hidden]. sFunc2
sFunc2 .r[hidden]. sFunc1

pDev1 <-- sInfo
sInfo <-- pDev2

sFunc2 <-- pCalc

pPres <-- sFunc1
sFunc1 <-- pCalc

footer **Replacing()** Breaking Changes - Public\n(C) DSP-Crowd Electronics GmbH

@enduml

