
@startuml

component "Company" as pComp1 {

database "Screen" as sScreen
database "Func A\nFunc B\nFunc C2" as sFunc2
database "Func A\nFunc B\nFunc C1\nFunc D" as sFunc1
file "Info\n<<Often missing>>" as sInfo

actor "Dev" as pAct1
component "Developing()" as pDev1

actor "Dev" as pAct2
component "Developing()" as pDev2

frame "Presenting()" as pPres
frame "Calculating()" as pCalc

pAct1 <-> pDev1
pDev1 -> pPres

pAct2 <-> pDev2
pDev2 -> pCalc
pPres -> sScreen

}

pDev1 <-- sInfo
sInfo <-- pDev2

sFunc2 .r[hidden]. sFunc1
sFunc2 <-- pCalc

pPres <-- sFunc1
sFunc1 <-- pCalc

footer **Replacing()** Breaking Changes - Private\n(C) DSP-Crowd Electronics GmbH

@enduml

