
@startuml

database "1. Existing()\nold process" as sOld {
  database "a" as a1
  database "b" as b1
  component "OldProcessing()" as op1
  
  a1 -> op1
  op1 -> b1
}

database "7. Existing()\nnew process" as sNew {
  database "a" as a7
  database "b" as b7
  component "NewProcessing()" as np7
  
  a7 -> np7
  np7 -> b7
}

actor "Developer\nUnOccupied" as sDev1
actor "Developer\nUnOccupied" as sDev2

component "Developing()" as pDev {

actor "Developer\nUnOccupied" as sDevUnOcc1
actor "Developer\nUnOccupied" as sDevUnOcc2

component "Replacing()" as pRep {

database "2. New process created" as sCreated {
  database "a" as a2
  database "b" as b2
  component "OldProcessing()" as op2
  component "NewProcessing()" as np2
  
  a2 -> np2
  a2 --> op2
  op2 -> b2
}

database "3. Copy" as sCopy {
  database "a" as a3
  database "b" as b3
  component "OldProcessing()" as op3
  component "NewProcessing()" as np3
  
  a3 -> np3
  a3 --> op3
  op3 -> b3
  np3 <-- op3
}

database "4. New process improved" as sImp {
  database "a" as a4
  database "b" as b4
  component "OldProcessing()" as op4
  component "NewProcessing()" as np4 #LightSteelBlue
  
  a4 -> np4
  a4 --> op4
  op4 -> b4
  np4 <--> op4
}

database "5. New process finished\nold process used" as sNewButOld {
  database "a" as a5
  database "b" as b5
  component "OldProcessing()" as op5
  component "NewProcessing()" as np5
  
  a5 -> np5
  a5 --> op5
  op5 -> b5
}

component "6. New process finished\nnew process used" as sNewAndNew {
  database "a" as a6
  database "b" as b6
  component "OldProcessing()" as op6
  component "NewProcessing()" as np6
  
  a6 -> np6
  np6 -> b6
  a6 --> op6
}

component "Creating()\nnew process" as pCreate
component "Copying()\nold process" as pCopy
component "Improving() / Comparing()\nuntil it's\nDominating()" as pImp
component "Beautifying()\nnew process" as pFin
component "Switching()\nto new process" as pSwitch
component "Releasing()" as pRel

pCreate --> sCreated
sCreated --> pCopy
pCopy --> sCopy
sCopy --> pImp
pImp --> sImp
sImp --> pFin
pFin --> sNewButOld
sNewButOld --> pSwitch
pSwitch --> sNewAndNew
sNewAndNew --> pRel

}

pRel -> sDevUnOcc2
sDevUnOcc1 -> pCreate

}

sOld --> pCreate
pRel --> sNew

sDev1 -> sDevUnOcc1
sDevUnOcc2 --> sDev2

footer **Replacing()** Overview \n(C) DSP-Crowd Electronics GmbH

@enduml

