
@startuml

' skinparam linetype ortho

frame "MsgDispatching()" as pMsg {

  frame "Initializing()" as pInit
  frame "ResultCreating()" as pParent

  frame "<< Vulkan Instance >>\nOwner: LibVulkan\nAccess: Global\n- Validation Layer\n- Messenger" as pInst
  frame "<< Vulkan Device >>\nOwner: LibVulkan\nAccess: Global by name\n- Physical\n- Logical\n- Pools\n- ..." as pDev
  frame "Vulkan Structure\nOwner/Lifetime: Parent\nAccess: Local\n- Descriptor Set\n- Buffers (R + RW)\n- ..." as pStruct
  frame "VulkanComputing()\nOwner/Lifetime: Parent\nAccess: Local\n- Result" as pComp

  pInit --> pInst : create
  pInit --> pDev : create

  pParent --> pStruct : create
  pParent --> pComp : create
  pParent <.. pDev : use

  pInst .> pDev : selected
  pDev .> pStruct : bound
  pStruct .> pComp : bound
}

footer **Vulkan** Abstraction - Computing()\n(C) DSP-Crowd Electronics GmbH

@enduml

