
name: FreeBSD

on:
  workflow_dispatch

jobs:

  freebsd-native-build-run:
    runs-on: ubuntu-latest
    steps:

      - name: Build in FreeBSD
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          prepare: |
            pkg install -y python git meson ninja cmake
          run: |
            git clone https://github.com/fractal-programming/FrapExamples.git --recursive
            cd FrapExamples
            for example in t01_tcp-echo-server t02_multithreading-mandelbrot t03_log-catching; do
              mkdir -p $example/build-native
              cd $example/build-native
              echo "=== Building $example ==="
              meson setup . ..
              meson compile
              ./app --help
              rm -rf *
              cmake ..
              cmake --build .
              ./app --help
              rm -rf *
              make -f ../Makefile -j
              ./app --help
              rm -rf *
              cd ../..
            done

